// ESLint flat config — TypeScript, React, Prettier compat
// Generated by @trinity369/use config-eslint-prettier

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

export default tseslint.config(
  // ── Global ignores ────────────────────────────────────────────────────────
  {
    ignores: ['node_modules/**', 'dist/**', '.next/**', 'coverage/**', 'build/**'],
  },

  // ── JavaScript recommended rules ──────────────────────────────────────────
  js.configs.recommended,

  // ── TypeScript strict rules ───────────────────────────────────────────────
  ...tseslint.configs.strict,

  // ── React recommended + JSX runtime ───────────────────────────────────────
  {
    ...react.configs.flat.recommended,
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  react.configs.flat['jsx-runtime'],

  // ── React Hooks ───────────────────────────────────────────────────────────
  {
    plugins: {
      'react-hooks': reactHooks,
    },
    rules: reactHooks.configs.recommended.rules,
  },

  // ── Shared language options & custom rules ────────────────────────────────
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2025,
      },
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    rules: {
      // Warn on console.log — remove before production
      'no-console': 'warn',

      // Allow unused vars prefixed with _ (common pattern for intentional ignores)
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },

  // ── Prettier compat (must be last) ────────────────────────────────────────
  eslintConfigPrettier,
);
