#!/usr/bin/env bash
set -euo pipefail

# Content Pipeline — helper script for managing the content creation workflow.
# Usage:
#   ./scripts/content-pipeline.sh init                          Create directory structure
#   ./scripts/content-pipeline.sh brief --type TYPE --topic "X" Generate a content brief
#   ./scripts/content-pipeline.sh status                        Show pipeline status

CONTENT_DIR="${CONTENT_DIR:-content}"
DATE=$(date +%Y-%m-%d)

slugify() {
  echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//'
}

cmd_init() {
  echo "Creating content directory structure..."
  mkdir -p "$CONTENT_DIR"/{research,drafts,published,style-guides,templates}

  # Create default style guide if not present
  if [ ! -f "$CONTENT_DIR/style-guides/default.md" ]; then
    cat > "$CONTENT_DIR/style-guides/default.md" << 'STYLE'
# Default Style Guide

## Voice and Tone
- Write in second person ("you") for tutorials, third person for case studies
- Keep a professional yet approachable tone
- Avoid jargon unless writing for a technical audience

## Formatting
- Use short paragraphs (2-4 sentences)
- Break up long sections with subheadings every 200-300 words
- Use bullet lists for 3+ related items
- Code blocks must specify a language for syntax highlighting

## Grammar
- Use the Oxford comma
- Prefer active voice over passive
- Keep sentences under 25 words when possible
- Spell out numbers under 10, use digits for 10+

## SEO
- Include primary keyword in H1 and first 100 words
- Use secondary keywords in H2/H3 subheadings naturally
- Meta title: under 60 characters
- Meta description: 120-160 characters, include a call to action
STYLE
    echo "  Created default style guide"
  fi

  echo "Done. Directory structure:"
  find "$CONTENT_DIR" -type d | sed 's/^/  /'
}

cmd_brief() {
  local type=""
  local topic=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --type) type="$2"; shift 2 ;;
      --topic) topic="$2"; shift 2 ;;
      *) echo "Unknown option: $1"; exit 1 ;;
    esac
  done

  if [ -z "$type" ] || [ -z "$topic" ]; then
    echo "Usage: $0 brief --type TYPE --topic \"Your Topic\""
    echo ""
    echo "Types: blog, documentation, newsletter, social, landing-page"
    exit 1
  fi

  local slug
  slug=$(slugify "$topic")
  local brief_file="$CONTENT_DIR/research/${DATE}-${slug}-brief.md"

  mkdir -p "$CONTENT_DIR/research"

  cat > "$brief_file" << BRIEF
# Content Brief: ${topic}

**Date**: ${DATE}
**Type**: ${type}
**Status**: Research

## Topic
${topic}

## Content Type
${type}

## Target Audience
<!-- Who will read this? What is their experience level? -->

## Primary Keyword
<!-- Main SEO target keyword -->

## Secondary Keywords
<!-- Supporting keyword list, comma-separated -->

## Tone
<!-- e.g., professional, conversational, technical, friendly -->

## Goal
<!-- What should the content achieve? educate / convert / engage / inform -->

## Word Count Target
<!-- Approximate desired length -->

## References
<!-- URLs, documents, or prior content to draw from -->
-
-
-

## Key Points to Cover
<!-- Main ideas that must be included -->
1.
2.
3.

## Deadline
<!-- Target completion date -->

---
*Generated by content-pipeline.sh on ${DATE}*
BRIEF

  echo "Brief created: $brief_file"
  echo "Edit the brief, then use the content-pipeline skill to proceed through the stages."
}

cmd_status() {
  echo "Content Pipeline Status"
  echo "======================"
  echo ""

  for stage in research drafts published; do
    count=$(find "$CONTENT_DIR/$stage" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l)
    echo "$stage: $count files"
    if [ "$count" -gt 0 ]; then
      find "$CONTENT_DIR/$stage" -maxdepth 1 -name "*.md" -printf "  %f\n" 2>/dev/null | sort | head -10
      if [ "$count" -gt 10 ]; then
        echo "  ... and $((count - 10)) more"
      fi
    fi
    echo ""
  done
}

# --- Main ---

case "${1:-help}" in
  init)    cmd_init ;;
  brief)   shift; cmd_brief "$@" ;;
  status)  cmd_status ;;
  help|*)
    echo "Content Pipeline"
    echo ""
    echo "Usage:"
    echo "  $0 init                              Create directory structure"
    echo "  $0 brief --type TYPE --topic \"X\"      Generate a content brief"
    echo "  $0 status                            Show pipeline status"
    echo ""
    echo "Content types: blog, documentation, newsletter, social, landing-page"
    ;;
esac
