import type { AuditLog } from "@/types";

export const mockAuditLogs: AuditLog[] = [
  {
    id: "a1",
    user_id: "1",
    user_email: "admin@example.com",
    user_name: "Admin User",
    action: "user.login",
    entity_type: "session",
    entity_id: null,
    metadata: {},
    ip_address: "192.168.1.1",
    created_at: "2024-06-01T08:00:00Z",
  },
  {
    id: "a2",
    user_id: "1",
    user_email: "admin@example.com",
    user_name: "Admin User",
    action: "user.create",
    entity_type: "user",
    entity_id: "4",
    metadata: { name: "Jane Cooper", role: "editor" },
    ip_address: "192.168.1.1",
    created_at: "2024-06-01T09:30:00Z",
  },
  {
    id: "a3",
    user_id: "2",
    user_email: "editor@example.com",
    user_name: "Editor User",
    action: "user.update",
    entity_type: "user",
    entity_id: "5",
    metadata: { field: "status", from: "active", to: "inactive" },
    ip_address: "10.0.0.42",
    created_at: "2024-06-02T14:15:00Z",
  },
  {
    id: "a4",
    user_id: "1",
    user_email: "admin@example.com",
    user_name: "Admin User",
    action: "settings.update",
    entity_type: "settings",
    entity_id: null,
    metadata: { section: "profile", field: "name" },
    ip_address: "192.168.1.1",
    created_at: "2024-06-03T11:00:00Z",
  },
  {
    id: "a5",
    user_id: "3",
    user_email: "viewer@example.com",
    user_name: "Viewer User",
    action: "user.login",
    entity_type: "session",
    entity_id: null,
    metadata: {},
    ip_address: "172.16.0.5",
    created_at: "2024-06-04T16:45:00Z",
  },
];
